// This file is generated by Sapper — do not edit it!
export const timestamp = 1547250607405;

export const files = [
	"favicon.ico",
	"global.css",
	"manifest.json",
	"michael-mosher.jpg"
];
export { files as assets }; // legacy

export const shell = [
	"client/chunk.3441c003.js",
	"client/client.7b0889f5.js",
	"client/chunk.728ccb9b.js"
];

export const routes = [
	{ pattern: /^\/?$/ }
];